export interface GeneralSettings {
	DigCheckered
	SurvivalZenMode
	SurvivalStartingLevel
	SprintLimit
	SprintPieceSet
	SprintBackfire
	RetroGameType
	RetroStartingLevel
	RetroSkin
	RetroHardDrop
	RetroFlashing
	MasterLock
	GradesGameRule
	MarathonGoal
	MarathonLevelCap
	MarathonEntryDelay
	MarathonNoGravity
	MarathonInvisible
}